logging:
  config: classpath:logback.xml
  path: d:/logs
server:
  port: 8074
  context-path: /data-transfer
  session-timeout: 60

mybatis:
  typeAliasesPackage: com.olderzhou.practice.dao    
  mapperScanPackage: com.olderzhou.practice.dao
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  
spring:
  profiles:
    active: @profileActive@    
  application:
    name: Yiconnect Data Transfer