logging:
  config: classpath:logback.xml
  path: d:/logs
server:
  port: 8074
  context-path: /data-transfer
  session-timeout: 60


mybatis:
  typeAliasesPackage: com.fei.springboot.dao    
  mapperScanPackage: com.fei.springboot.dao
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml

spring:
    datasource:
        name: db
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/im_log_service_2?useUnicode=true&amp;characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat  